version: 2
jobs:
  build:

    working_directory: ~/repo

    machine:
      python:
        version: pyenv 2.7.12
      enabled: true

    steps:
      - checkout
      - run:
          name: Installing
          command: |
            sudo -H bash base_installation.sh
      