version: 2
jobs:
  build:

    working_directory: ~/repo

    machine:
      python:
        version: pyenv 2.7.12
      enabled: true

    steps:
        - checkout

        # Restore pip dependencies
        - restore_cache:
            keys:
            - v1-pip-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found.
            - v1-pip-dependencies-

        # Restore homebrew dependencies
        - restore_cache:
            keys:
            - v1-brew-dependencies-{{ checksum "install_brewed_dependencies.sh" }}
            - v1-brew-dependencies-

        # Restore general dependencies
        - restore_cache:
            keys:
            - v1-general-dependencies-{{ checksum "base_installation.sh" }}
            - v1-general-dependencies-

        # Install dependencies and applications
        - run:
            name: Install Dependencies
            command: |
              sudo apt-get install build-essential python-dev curl file git python-setuptools ruby
              ./base_installation.sh

        # Cache python dependencies
        - save_cache:
            paths:
              - ~/.local/lib/python2.7
            key: v1-pip-dependencies-{{ checksum "requirements.txt" }}

        # Cache homebrew dependencies
        - save_cache:
            paths:
              - ~/.linuxbrew
            key: v1-brew-dependencies-{{ checksum "install_brewed_dependencies.sh" }}

        # Cache all other dependencies and data
        - save_cache:
            paths:
              - ~/repo/data
            key: v1-general-dependencies-{{ checksum "base_installation.sh" }}

        # Run the Unit Tests
        - run:
            name: Unit Testing
            command: |
              export PATH="$HOME/.linuxbrew/bin:$PATH"
              cd testing
              nosetests -v

        # Run the end-to-end test
        - run:
            name: End-to-end Testing
            command: |
              export PATH="$HOME/.linuxbrew/bin:$PATH"
              /usr/bin/env bash -eo pipefail ./testing/test_metannotate_end_to_end.sh
