# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
machine:
  python:
    version: python-2.7.1
jobs:
  build:
    machine: true

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            virtualenv .venv/bin/activate
            sudo -H bash base_installation.sh

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run tests!
      - run:
          name: run tests
          command: |
            sudo bash test_metannotate.sh
            cd testing
            nosetests -v

      - store_artifacts:
          path: test-reports
          destination: test-reports

