version: 2
jobs:
  build:

    working_directory: ~/repo

    machine:
      python:
        version: pyenv 2.7.12
      enabled: true

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            virtualenv .venv/bin/activate
            sudo apt-get install build-essential python-dev curl file git python-setuptools ruby
      - run:
          name: run tests
          command: |
            mkdir -p ~/.local/bin/
            export TERM=xterm
            ./base_installation.sh
            ./test_metannotate.sh
            cd testing
            nosetests -v
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
