version: 2
jobs:
  build:

    working_directory: ~/repo

    machine:
      python:
        version: pyenv 2.7.12
      enabled: true

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            virtualenv .venv/bin/activate
            sudo apt-get install build-essential curl file git python-setuptools ruby
      - run:
          name: run tests
          command: |
            sudo mkdir -p ~/.local/bin/
            sudo export TERM=xterm
            sudo bash base_installation.sh
            sudo bash test_metannotate.sh
            cd testing
            nosetests -v